# 0. Quarkus 기본 포트
quarkus.http.port=8080
# 1. 홈페이지 기본 시작 페이지
quarkus.http.static-resources.index-page=index.html
# 2. 서버 시작시 테스트 패스
quarkus.test.continuous-testing=disabled

# 데이터베이스 연결 설정
quarkus.datasource.db-kind=mysql
quarkus.datasource.username=root
quarkus.datasource.password=123123
quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3306/lol

# Hibernate 설정
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true